version: "3.9"
services:
  server:
    container_name: server
    image: server:latest
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  thermometer:
    container_name: thermometer
    image: thermometer:latest
    build:
      context: .
      dockerfile: ./docker/thermometer.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U admin -d postgres',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none